export const editorConfig = {
  saveToPhoto: true,
  outputExt: "mp4",
  saveButtonText: "Avançar",
  cancelButtonText: "Cancelar",
  saveDialogConfirmText: "Salvar",
  saveDialogCancelText: "Cancelar",
  saveDialogTitle: "Salvar vídeo",
  saveDialogMessage: "Tem certeza que quer salvar a edição?",
  cancelDialogCancelText: "Fechar",
  cancelDialogConfirmText: "Prosseguir",
  cancelDialogTitle: "Cancelar edição",
  cancelDialogMessage: "Tem certeza que quer cancelar a edição?",
  trimmingText: "Cortando...",
  cancelTrimmingButtonText: "Cancelar",
  cancelTrimmingDialogCancelText: "Fechar",
  cancelTrimmingDialogConfirmText: "Prosseguir",
  cancelTrimmingDialogTitle: "Cancelar corte",
  cancelTrimmingDialogMessage: "Tem certeza que quer cancelar o corte?",
  enableCancelTrimming: true,
};
